### ISSUE TITLE
What's the magic number -2.19 mean?

### ISSUE THREAD

**Issue by lufo816** [princeton-vl/CornerNet#13]
In kp.py
        # for tl_heat, br_heat in zip(self.tl_heats, self.br_heats):
        #     tl_heat[-1].bias.data.fill_(-2.19)
        #     br_heat[-1].bias.data.fill_(-2.19)

**Comment by heilaw** [comment]
We set the bias following the formula given in Section 4.1 of the [focal loss paper](https://arxiv.org/abs/1708.02002). We use pi equals to 0.1.
