### ISSUE TITLE
Segmentation fault when training on my own data.

### ISSUE THREAD

**Issue by zxDeepDiver** [princeton-vl/CornerNet#20]
Hi,

Thank you for your wonderful work. But after I simply change the path to my own dataset (all pictures with the size of 1280x720), I meet the segmentation fault. :( Can you please help me locate the bug?

![image](https://user-images.githubusercontent.com/7352077/45417012-c1b3fe00-b6b3-11e8-92bd-c0f49024ba2a.png)

**Comment by heilaw** [comment]
It could be related to the corner pooling compilation. Can you try [this](https://github.com/umich-vl/CornerNet/issues/6)? Also, can you provide the full screenshot that includes the full configuration details? That may help.

**Comment by zxDeepDiver** [comment]
Thank you. Updating gcc from 4.8 to 4.9.4 solved this problem.

**Comment by jiachen0212** [comment]
hello @zxDeepDiver , i also meet the bug:
training start...
  0%|                                                | 0/500000 [00:00<?, ?it/s]Segmentation fault
you mean that updataing the gcc to 4.94 can solve this bug?
