### ISSUE TITLE
loading parameters... loading model from ./cache/nnet/CornerNet/CornerNet_500.pkl locating kps: 100%|███████████████████████████████| 

### ISSUE THREAD

**Issue by lianbobo** [princeton-vl/CornerNet#28]

**Comment by lianbobo** [comment]
When I testing, only get the result.json file, but don't get any image

**Comment by ekremcet** [comment]
To draw the results on image files you need some modifications in `CornerNet/test/coco.py `

- make Line 153 `if True:`
- below Line 193 `debug_file = os.path.join(debug_dir, "{}.jpg".format(db_ind))`
add `cv2.imwrite(debug_file, image)`

that should save images to `CornerNet/results/CornerNet/500000/validation`

**Comment by lianbobo** [comment]
This also solved my problem. Very thanks!
