### ISSUE TITLE
any plan to write demo.py ?

### ISSUE THREAD

**Issue by spytensor** [princeton-vl/CornerNet#36]
as the title,if you have plan to write a demo.py for this repo?

**Comment by planckztd** [comment]
I need a demo to visualize the trained result,too

**Comment by xiaoxiongli** [comment]
i need a demo.py to do like :   input:  xxx.jpg,     output: boundingbox and score..., how can i do it?

**Comment by xingyizhou** [comment]
Hi, 
  I have contributed one at https://github.com/princeton-vl/CornerNet/pull/60 .

**Comment by chordxu** [comment]
When I change and add the codes which listed by you,  does it only need to run "visualize.py" that I could visualize the heatmap? @xingyizhou
