### ISSUE TITLE
What is the general operation of the backward of corner pooling?

### ISSUE THREAD

**Issue by CasonTsai** [princeton-vl/CornerNet#66]
excuse me,I am currently reading about the code of corner pooling layer,I think I understand the forward of the corner pooling ,but i don't quite understand the backward ,could you Explain the general process of backward?
![image](https://user-images.githubusercontent.com/18262642/50724628-c5b8cf80-112b-11e9-89f1-4078b0a3f76e.png)

**Comment by heilaw** [comment]
It's similar to the conventional max pooling. The gradients back propagate through the neurons that achieve the maximum values.
