### ISSUE TITLE
incorrect annotation link

### ISSUE THREAD

**Issue by hannahorn** [princeton-vl/CornerNet#88]
Link that is supposed to be the annotation file sends me to the 500k trained pkl file:

This link:
Download the training/validation split we use in our paper from **here** (originally from Faster R-CNN)
Unzip the file and place annotations under <CornerNet dir>/data/coco

and this link:
 We also provide a trained model for CornerNet, which is trained for 500k iterations using 10 Titan X (PASCAL) GPUs. You can download it from here

are the same and the annotation.zip is missing

**Comment by heilaw** [comment]
Fixed.

**Comment by hannahorn** [comment]
Thank you for the fast reply!

**Comment by mrlaiii** [comment]
i am locate in china,and i can't download the coco annotation.when i click the this link
Download the training/validation split we use in our paper from here (originally from Faster R-CNN)
Unzip the file and place annotations under /data/coco 
it is always loading.
My guess is that there is something wrong with the server
